import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = path.join(import.meta.dirname, "..");
const out = path.join(root, "lib", "pricing-snapshot.js");
const LLM_PRICES_URL = "https://www.llm-prices.com/current-v1.json";
const OPENROUTER_URL = "https://openrouter.ai/api/v1/models";

function rate(value, multiplier = 1) {
  const n = Number(value);
  return Number.isFinite(n) && n >= 0 ? n * multiplier : null;
}

function normalizeOpenRouter(json) {
  if (!Array.isArray(json?.data)) throw new Error("OpenRouter payload has no data array");
  return json.data.flatMap((model) => {
    const inputRate = rate(model?.pricing?.prompt, 1e6);
    const outputRate = rate(model?.pricing?.completion, 1e6);
    return inputRate == null || outputRate == null ? [] : [{
      source: "openrouter", id: String(model.id).toLowerCase(), inputRate, outputRate,
    }];
  });
}

function normalizeLlmPrices(json) {
  if (!Array.isArray(json?.prices)) throw new Error("llm-prices payload has no prices array");
  return json.prices.flatMap((model) => {
    const inputRate = rate(model.input);
    const outputRate = rate(model.output);
    return inputRate == null || outputRate == null ? [] : [{
      source: "llm-prices", id: String(model.id).toLowerCase(), inputRate, outputRate,
    }];
  });
}

async function getJson(url) {
  // A pricing refresh is opportunistic. Bound it so an unavailable catalogue
  // cannot hold up the production bundle; the existing snapshot remains live.
  const response = await fetch(url, { signal: AbortSignal.timeout(10_000) });
  if (!response.ok) throw new Error(`${url} HTTP ${response.status}`);
  return response.json();
}

try {
  const [openRouter, llmPrices] = await Promise.all([getJson(OPENROUTER_URL), getJson(LLM_PRICES_URL)]);
  const snapshot = {
    generatedAt: new Date().toISOString(),
    sources: {
      openrouter: { updatedAt: new Date().toISOString() },
      "llm-prices": { updatedAt: llmPrices.updated_at || null },
    },
    prices: [...normalizeOpenRouter(openRouter), ...normalizeLlmPrices(llmPrices)],
  };
  if (!snapshot.prices.length) throw new Error("pricing catalogue contained no usable records");
  await writeFile(out, `// Generated by scripts/refresh-pricing.js. Do not edit manually.\nexport const PRICING_SNAPSHOT = ${JSON.stringify(snapshot, null, 2)};\n`);
  console.log(`Pricing snapshot refreshed (${snapshot.prices.length} records).`);
} catch (error) {
  // A valid committed snapshot makes pricing work offline; refresh failure must
  // never turn an external catalogue outage into a failed deployment.
  await readFile(out, "utf8");
  console.warn(`Pricing snapshot unchanged: ${error.message}`);
}
